### ISSUE TITLE
When is next version?

### ISSUE THREAD

**Issue by MattCollins84** [elad/node-imagemagick-native#108]
Hi,

We are updating our app to use Node 4.2.1 and are currently using 1.7.0 of your module.

We have found that neither 1.7.0 or 1.8.0 build on node 4.2.1, but the current master branch of this module will, which is great, except that I am a bit wary of putting a reference direct to the master branch of your package in my package.json.

Is there an ETA on the release of 1.9.0?

Thanks,
Matt

**Comment by elad** [comment]
Yes, shortly, probably later on today. :)

**Comment by toddself** [comment]
still can't build on node 4.2.1, but i can install `elad/node-imagemagick-native` and it works. looks like package.json is still out of date w/r/t to master?

**Comment by elad** [comment]
Sorry for the huge delay. Just released the master branch as 1.9.0.
