### ISSUE TITLE
issue compiling with nodejs 5.5

### ISSUE THREAD

**Issue by ckross01** [elad/node-imagemagick-native#117]
I am having an issue after upgrading to nodejs 5.5. 

`Package Magick++ was not found in the pkg-config search path.
Perhaps you should add the directory containing`Magick++.pc'
to the PKG_CONFIG_PATH environment variable
No package 'Magick++' found
Package Magick++ was not found in the pkg-config search path.
Perhaps you should add the directory containing `Magick++.pc'
to the PKG_CONFIG_PATH environment variable
No package 'Magick++' found
gyp: Call to 'Magick++-config --ldflags --libs' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error:`gyp`failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/CRoss/dev/node-imagemagick-native/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/Users/MyUser/.nvm/versions/node/v5.5.0/bin/node" "/Users/MyUser/dev/node-imagemagick-native/node_modules/.bin/node-gyp" "configure"
gyp ERR! cwd /Users/CRoss/dev/node-imagemagick-native
gyp ERR! node -v v5.5.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok`

Current using Mac OSX 10.11.3 and failed on installing with the same error for ubuntu 14.04.

Anyone else having a similar issue?

**Comment by dustingraves** [comment]
Did you resolve this? I had to update xcode and make sure I was running latest command line tools. In addition `brew install pkgconfig` then `brew remove imagemagick` and `brew install imagemagick` then retry.

**Comment by ckross01** [comment]
Nope, haven't resolved yet but let me give those steps a try and then I'll update. Ty

**Comment by mallocator** [comment]
FYI: remove (--force) and install worked for me with nodejs@7.2.1 and imagemagick-native@1.9.3.

**Comment by ckross01** [comment]
That did the trick. Thanks.
