### ISSUE TITLE
Can you support -flatten in convert 

### ISSUE THREAD

**Issue by TechGuyVN** [elad/node-imagemagick-native#125]
Hi,

Thanks for incredible code, supper fast in convert image compare with imagemagick console porting.
My case i use IONIC to generate splash.png image, but the PNG image output have transparent pixel so ionic can not understand it.
I figure out i can use image magick with option -flatten to solve this problem.
So can you provide a build support flatten convert mode ?

Many thanks!

**Comment by rchipka** [comment]
Fixed by #140 with the option `{ background: "white" }`.
