### ISSUE TITLE
Installation fails on Mac OSX for NodeJS@8.0.0 (brew imagemagick@7.0.5-9) (used to work fine on NodeJS@7)

### ISSUE THREAD

**Issue by Thesephi** [elad/node-imagemagick-native#170]
So, as the title suggested, the version info is as followed:

- NodeJS@8.0.0
- npm@5.0.1
- imagemagick@7.0.5-9 (installed with Homebrew)
- MacOS 10.12.5

As I ran `npm install imagemagick-native` , the stack returned is as pasted [here](https://gist.github.com/Thesephi/6dbdf4a2e2dc92f09ee9016384e66f2e).

Thank you much for any insight / advices. Also, apologies i couldn't help more due to the lack of exp in writing native npm modules 😞 

*Edited*: i also tried on **Ubuntu 14.04.5 LTS and it works there**, which makes this an issue **on my Mac OS only thus far** (I haven't tested on Windows).

**Comment by cartuchogl** [comment]
Could you try with imagemagick 6.9.x ? I think that imm 7.x is not supported yet

**Comment by Thesephi** [comment]
Thanks a lot @cartuchogl . I did and it WORKS ! Procedure was as followed:

1. `brew install imagemagick@6`
2. notice im6 is a keg-only formula, so: 
```
export PATH="/usr/local/opt/imagemagick@6/bin:$PATH"
export PKG_CONFIG_PATH="/usr/local/opt/imagemagick@6/lib/pkgconfig"
npm install imagemagick-native
```

This definitely can save the day and gets the build done for lots of folks out there 😃 . To imagemagick@7: we shall meet another day.
