### ISSUE TITLE
Does not work with ImageMagick 7

### ISSUE THREAD

**Issue by zebroc** [elad/node-imagemagick-native#180]
Gentoo, media-gfx/imagemagick-7.0.7.19.

Getting this:

  CXX(target) Release/obj.target/imagemagick/src/imagemagick.o
../src/imagemagick.cc: In function ‘void DoConvert(uv_work_t*)’:
../src/imagemagick.cc:262:32: error: ‘FilterTypes’ is not a member of ‘Magick’
             image.filterType( (Magick::FilterTypes)option_info );
                                ^~~~~~
../src/imagemagick.cc:327:84: error: no matching function for call to ‘Magick::Geometry::Geometry(unsigned int&, unsigned int&, int, int, int, int)’
             Magick::Geometry resizeGeometry( resizewidth, resizeheight, 0, 0, 0, 0 );
                                                                                    ^
In file included from /usr/include/ImageMagick-7/Magick++/Drawable.h:28:0,
                 from /usr/include/ImageMagick-7/Magick++/Image.h:17,
                 from /usr/include/ImageMagick-7/Magick++.h:12,
                 from ../src/imagemagick.h:1,
                 from ../src/imagemagick.cc:9:
/usr/include/ImageMagick-7/Magick++/Geometry.h:119:5: note: candidate: Magick::Geometry::Geometry(const RectangleInfo&)
     Geometry(const MagickCore::RectangleInfo &rectangle_);
     ^~~~~~~~
/usr/include/ImageMagick-7/Magick++/Geometry.h:119:5: note:   candidate expects 1 argument, 6 provided
/usr/include/ImageMagick-7/Magick++/Geometry.h:52:5: note: candidate: Magick::Geometry::Geometry(size_t, size_t, ssize_t, ssize_t)
     Geometry(size_t width_,size_t height_,::ssize_t xOff_=0,
     ^~~~~~~~
/usr/include/ImageMagick-7/Magick++/Geometry.h:52:5: note:   candidate expects 4 arguments, 6 provided
/usr/include/ImageMagick-7/Magick++/Geometry.h:49:5: note: candidate: Magick::Geometry::Geometry(const string&)
     Geometry(const std::string &geometry_);
     ^~~~~~~~
/usr/include/ImageMagick-7/Magick++/Geometry.h:49:5: note:   candidate expects 1 argument, 6 provided
/usr/include/ImageMagick-7/Magick++/Geometry.h:46:5: note: candidate: Magick::Geometry::Geometry(const Magick::Geometry&)
     Geometry(const Geometry &geometry_);
     ^~~~~~~~
/usr/include/ImageMagick-7/Magick++/Geometry.h:46:5: note:   candidate expects 1 argument, 6 provided
/usr/include/ImageMagick-7/Magick++/Geometry.h:43:5: note: candidate: Magick::Geometry::Geometry(const char*)
     Geometry(const char *geometry_);
     ^~~~~~~~
/usr/include/ImageMagick-7/Magick++/Geometry.h:43:5: note:   candidate expects 1 argument, 6 provided
/usr/include/ImageMagick-7/Magick++/Geometry.h:40:5: note: candidate: Magick::Geometry::Geometry()
     Geometry();
     ^~~~~~~~
/usr/include/ImageMagick-7/Magick++/Geometry.h:40:5: note:   candidate expects 0 arguments, 6 provided
../src/imagemagick.cc:345:86: error: no matching function for call to ‘Magick::Geometry::Geometry(unsigned int&, unsigned int&, unsigned int&, unsigned int&, int, int)’
                 Magick::Geometry cropGeometry( width, height, xoffset, yoffset, 0, 0 );
                                                                                      ^
In file included from /usr/include/ImageMagick-7/Magick++/Drawable.h:28:0,
                 from /usr/include/ImageMagick-7/Magick++/Image.h:17,
                 from /usr/include/ImageMagick-7/Magick++.h:12,
                 from ../src/imagemagick.h:1,
                 from ../src/imagemagick.cc:9:
/usr/include/ImageMagick-7/Magick++/Geometry.h:119:5: note: candidate: Magick::Geometry::Geometry(const RectangleInfo&)
     Geometry(const MagickCore::RectangleInfo &rectangle_);
     ^~~~~~~~
/usr/include/ImageMagick-7/Magick++/Geometry.h:119:5: note:   candidate expects 1 argument, 6 provided
/usr/include/ImageMagick-7/Magick++/Geometry.h:52:5: note: candidate: Magick::Geometry::Geometry(size_t, size_t, ssize_t, ssize_t)
     Geometry(size_t width_,size_t height_,::ssize_t xOff_=0,
     ^~~~~~~~
/usr/include/ImageMagick-7/Magick++/Geometry.h:52:5: note:   candidate expects 4 arguments, 6 provided
/usr/include/ImageMagick-7/Magick++/Geometry.h:49:5: note: candidate: Magick::Geometry::Geometry(const string&)
     Geometry(const std::string &geometry_);
     ^~~~~~~~
/usr/include/ImageMagick-7/Magick++/Geometry.h:49:5: note:   candidate expects 1 argument, 6 provided
/usr/include/ImageMagick-7/Magick++/Geometry.h:46:5: note: candidate: Magick::Geometry::Geometry(const Magick::Geometry&)
     Geometry(const Geometry &geometry_);
     ^~~~~~~~
/usr/include/ImageMagick-7/Magick++/Geometry.h:46:5: note:   candidate expects 1 argument, 6 provided
/usr/include/ImageMagick-7/Magick++/Geometry.h:43:5: note: candidate: Magick::Geometry::Geometry(const char*)
     Geometry(const char *geometry_);
     ^~~~~~~~
/usr/include/ImageMagick-7/Magick++/Geometry.h:43:5: note:   candidate expects 1 argument, 6 provided
/usr/include/ImageMagick-7/Magick++/Geometry.h:40:5: note: candidate: Magick::Geometry::Geometry()
     Geometry();
     ^~~~~~~~
/usr/include/ImageMagick-7/Magick++/Geometry.h:40:5: note:   candidate expects 0 arguments, 6 provided
../src/imagemagick.cc:351:33: error: ‘class Magick::Color’ has no member named ‘alpha’
                     transparent.alpha( 1. );
                                 ^~~~~
../src/imagemagick.cc:425:75: error: no matching function for call to ‘Magick::Image::density(Magick::Geometry)’
         image.density(Magick::Geometry(context->density, context->density));
                                                                           ^
In file included from /usr/include/ImageMagick-7/Magick++.h:12:0,
                 from ../src/imagemagick.h:1,
                 from ../src/imagemagick.cc:9:
/usr/include/ImageMagick-7/Magick++/Image.h:208:10: note: candidate: void Magick::Image::density(const Magick::Point&)
     void density(const Point &density_);
          ^~~~~~~
/usr/include/ImageMagick-7/Magick++/Image.h:208:10: note:   no known conversion for argument 1 from ‘Magick::Geometry’ to ‘const Magick::Point&’
/usr/include/ImageMagick-7/Magick++/Image.h:209:11: note: candidate: Magick::Point Magick::Image::density() const
     Point density(void) const;
           ^~~~~~~
/usr/include/ImageMagick-7/Magick++/Image.h:209:11: note:   candidate expects 0 arguments, 1 provided
../src/imagemagick.cc: In function ‘void BuildIdentifyResult(uv_work_t*, v8::Local<v8::Value>*)’:
../src/imagemagick.cc:646:58: error: conversion from ‘Magick::Point’ to non-scalar type ‘Magick::Geometry’ requested
         Magick::Geometry density = context->image.density();
                                    ~~~~~~~~~~~~~~~~~~~~~~^~
../src/imagemagick.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE GetConstPixels(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/imagemagick.cc:803:19: error: ‘PixelPacket’ in namespace ‘Magick’ does not name a type
     const Magick::PixelPacket *pixels = image.getConstPixels(xValue, yValue, columnsValue, rowsValue);
                   ^~~~~~~~~~~
../src/imagemagick.cc:807:9: error: ‘PixelPacket’ is not a member of ‘Magick’
         Magick::PixelPacket pixel = pixels[ i ];
         ^~~~~~
../src/imagemagick.cc:807:9: note: suggested alternative:
In file included from /usr/include/ImageMagick-7/MagickCore/stream.h:25:0,
                 from /usr/include/ImageMagick-7/MagickCore/blob.h:48,
                 from /usr/include/ImageMagick-7/MagickCore/image.h:131,
                 from /usr/include/ImageMagick-7/MagickCore/draw.h:22,
                 from /usr/include/ImageMagick-7/MagickCore/annotate.h:21,
                 from /usr/include/ImageMagick-7/MagickCore/MagickCore.h:82,
                 from /usr/include/ImageMagick-7/Magick++/Include.h:42,
                 from /usr/include/ImageMagick-7/Magick++.h:10,
                 from ../src/imagemagick.h:1,
                 from ../src/imagemagick.cc:9:
/usr/include/ImageMagick-7/MagickCore/pixel.h:204:3: note:   ‘MagickCore::PixelPacket’
 } PixelPacket;
   ^~~~~~~~~~~
../src/imagemagick.cc:810:84: error: ‘pixel’ was not declared in this scope
         color->Set(Nan::New<String>("red").ToLocalChecked(),     Nan::New<Integer>(pixel.red));
                                                                                    ^~~~~
../src/imagemagick.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE QuantizeColors(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/imagemagick.cc:874:64: error: no matching function for call to ‘Magick::Geometry::Geometry(ssize_t&, ssize_t&, int, int, int, int)’
     Magick::Geometry resizeGeometry( rows, columns, 0, 0, 0, 0 );
                                                                ^
In file included from /usr/include/ImageMagick-7/Magick++/Drawable.h:28:0,
                 from /usr/include/ImageMagick-7/Magick++/Image.h:17,
                 from /usr/include/ImageMagick-7/Magick++.h:12,
                 from ../src/imagemagick.h:1,
                 from ../src/imagemagick.cc:9:
/usr/include/ImageMagick-7/Magick++/Geometry.h:119:5: note: candidate: Magick::Geometry::Geometry(const RectangleInfo&)
     Geometry(const MagickCore::RectangleInfo &rectangle_);
     ^~~~~~~~
/usr/include/ImageMagick-7/Magick++/Geometry.h:119:5: note:   candidate expects 1 argument, 6 provided
/usr/include/ImageMagick-7/Magick++/Geometry.h:52:5: note: candidate: Magick::Geometry::Geometry(size_t, size_t, ssize_t, ssize_t)
     Geometry(size_t width_,size_t height_,::ssize_t xOff_=0,
     ^~~~~~~~
/usr/include/ImageMagick-7/Magick++/Geometry.h:52:5: note:   candidate expects 4 arguments, 6 provided
/usr/include/ImageMagick-7/Magick++/Geometry.h:49:5: note: candidate: Magick::Geometry::Geometry(const string&)
     Geometry(const std::string &geometry_);
     ^~~~~~~~
/usr/include/ImageMagick-7/Magick++/Geometry.h:49:5: note:   candidate expects 1 argument, 6 provided
/usr/include/ImageMagick-7/Magick++/Geometry.h:46:5: note: candidate: Magick::Geometry::Geometry(const Magick::Geometry&)
     Geometry(const Geometry &geometry_);
     ^~~~~~~~
/usr/include/ImageMagick-7/Magick++/Geometry.h:46:5: note:   candidate expects 1 argument, 6 provided
/usr/include/ImageMagick-7/Magick++/Geometry.h:43:5: note: candidate: Magick::Geometry::Geometry(const char*)
     Geometry(const char *geometry_);
     ^~~~~~~~
/usr/include/ImageMagick-7/Magick++/Geometry.h:43:5: note:   candidate expects 1 argument, 6 provided
/usr/include/ImageMagick-7/Magick++/Geometry.h:40:5: note: candidate: Magick::Geometry::Geometry()
     Geometry();
     ^~~~~~~~
/usr/include/ImageMagick-7/Magick++/Geometry.h:40:5: note:   candidate expects 0 arguments, 6 provided
../src/imagemagick.cc:884:5: error: ‘PixelPacket’ is not a member of ‘Magick’
     Magick::PixelPacket* pixels = image.getPixels(0, 0, image.columns(), image.rows());
     ^~~~~~
../src/imagemagick.cc:884:5: note: suggested alternative:
In file included from /usr/include/ImageMagick-7/MagickCore/stream.h:25:0,
                 from /usr/include/ImageMagick-7/MagickCore/blob.h:48,
                 from /usr/include/ImageMagick-7/MagickCore/image.h:131,
                 from /usr/include/ImageMagick-7/MagickCore/draw.h:22,
                 from /usr/include/ImageMagick-7/MagickCore/annotate.h:21,
                 from /usr/include/ImageMagick-7/MagickCore/MagickCore.h:82,
                 from /usr/include/ImageMagick-7/Magick++/Include.h:42,
                 from /usr/include/ImageMagick-7/Magick++.h:10,
                 from ../src/imagemagick.h:1,
                 from ../src/imagemagick.cc:9:
/usr/include/ImageMagick-7/MagickCore/pixel.h:204:3: note:   ‘MagickCore::PixelPacket’
 } PixelPacket;
   ^~~~~~~~~~~
../src/imagemagick.cc:884:26: error: ‘pixels’ was not declared in this scope
     Magick::PixelPacket* pixels = image.getPixels(0, 0, image.columns(), image.rows());
                          ^~~~~~
../src/imagemagick.cc:886:5: error: ‘PixelPacket’ is not a member of ‘Magick’
     Magick::PixelPacket* colors = new Magick::PixelPacket[colorsCount]();
     ^~~~~~
../src/imagemagick.cc:886:5: note: suggested alternative:
In file included from /usr/include/ImageMagick-7/MagickCore/stream.h:25:0,
                 from /usr/include/ImageMagick-7/MagickCore/blob.h:48,
                 from /usr/include/ImageMagick-7/MagickCore/image.h:131,
                 from /usr/include/ImageMagick-7/MagickCore/draw.h:22,
                 from /usr/include/ImageMagick-7/MagickCore/annotate.h:21,
                 from /usr/include/ImageMagick-7/MagickCore/MagickCore.h:82,
                 from /usr/include/ImageMagick-7/Magick++/Include.h:42,
                 from /usr/include/ImageMagick-7/Magick++.h:10,
                 from ../src/imagemagick.h:1,
                 from ../src/imagemagick.cc:9:
/usr/include/ImageMagick-7/MagickCore/pixel.h:204:3: note:   ‘MagickCore::PixelPacket’
 } PixelPacket;
   ^~~~~~~~~~~
../src/imagemagick.cc:886:26: error: ‘colors’ was not declared in this scope
     Magick::PixelPacket* colors = new Magick::PixelPacket[colorsCount]();
                          ^~~~~~
../src/imagemagick.cc:886:47: error: ‘PixelPacket’ in namespace ‘Magick’ does not name a type
     Magick::PixelPacket* colors = new Magick::PixelPacket[colorsCount]();
                                               ^~~~~~~~~~~
../src/imagemagick.cc:891:13: error: ‘PixelPacket’ is not a member of ‘Magick’
             Magick::PixelPacket pixel = pixels[rows * x + y];
             ^~~~~~
../src/imagemagick.cc:891:13: note: suggested alternative:
In file included from /usr/include/ImageMagick-7/MagickCore/stream.h:25:0,
                 from /usr/include/ImageMagick-7/MagickCore/blob.h:48,
                 from /usr/include/ImageMagick-7/MagickCore/image.h:131,
                 from /usr/include/ImageMagick-7/MagickCore/draw.h:22,
                 from /usr/include/ImageMagick-7/MagickCore/annotate.h:21,
                 from /usr/include/ImageMagick-7/MagickCore/MagickCore.h:82,
                 from /usr/include/ImageMagick-7/Magick++/Include.h:42,
                 from /usr/include/ImageMagick-7/Magick++.h:10,
                 from ../src/imagemagick.h:1,
                 from ../src/imagemagick.cc:9:
/usr/include/ImageMagick-7/MagickCore/pixel.h:204:3: note:   ‘MagickCore::PixelPacket’
 } PixelPacket;
   ^~~~~~~~~~~
../src/imagemagick.cc:895:21: error: ‘pixel’ was not declared in this scope
                 if (pixel.red == colors[x].red && pixel.green == colors[x].green && pixel.blue == colors[x].blue) found = true;
                     ^~~~~
../src/imagemagick.cc:897:43: error: ‘pixel’ was not declared in this scope
             if (!found) colors[index++] = pixel;
                                           ^~~~~
../src/imagemagick.cc:931:14: error: type ‘<type error>’ argument given to ‘delete’, expected pointer
     delete[] colors;
              ^~~~~~
make: *** [imagemagick.target.mk:108: Release/obj.target/imagemagick/src/imagemagick.o] Error 1

**Comment by cartuchogl** [comment]
At this moment only 6.x are supported. To support 6.x and 7.x at same time need many changes on native code. Pull requests are wellcome ;)

**Comment by cartuchogl** [comment]
Some old work merged with current master on https://github.com/cartuchogl/node-imagemagick-native/tree/im7
