### ISSUE TITLE
Node 12 support

### ISSUE THREAD

**Issue by florianreinhart** [elad/node-imagemagick-native#193]
The native extension does not build with Node 12.

**Comment by nyuszika7h** [comment]
Now I know why it was erroring. I reverted to Node 10 LTS and that worked fine.

**Comment by kamil-cf** [comment]
[node-10.15.log](https://github.com/elad/node-imagemagick-native/files/3248370/node-10.15.log)
[node-12.log](https://github.com/elad/node-imagemagick-native/files/3248371/node-12.log)
Works on v10.15, doesn't work on v12. Logs attached.

**Comment by renatocron** [comment]
https://github.com/elad/node-imagemagick-native/pull/195

this pull request is open for a few months now

**Comment by abetomo** [comment]
#195 closed.
#199 now also supports Node.js14.

**Comment by TimWolla** [comment]
This is resolved now. Thanks @abetomo!
