### ISSUE TITLE
Provided benchmark correct only for small files

### ISSUE THREAD

**Issue by laszbalo** [elad/node-imagemagick-native#46]
I have ran your benchmark with medium/large size images and got completely different result.
According to my measurements, imagemagick-native was 1.5/3 times slower than imagemagick.

I have tested it with [this photo](http://wallpaperswide.com/platform_9_and_three_quarters-wallpapers.html).

I downloaded the "Standard 4:3" and "HD 16:9" sizes of the same photo.

Here are my results:
1. Provided test.jpg, 6.9 kB, 58x66
   imagemagick:       15.23ms per iteration
   imagemagick-native: 1.45ms per iteration
   Winner: **imagemagick-native** is _1050%_  faster
2. Above wallpaper, standard, 139.3 kB, 800x600
   imagemagick:       33.06ms per iteration
   imagemagick-native: 47.16ms per iteration
   Winner: **imagemagick** is _142%_ faster
3. Above wallpaper, standard, 1.0 MB, 2800x2100
   imagemagick:       248ms per iteration
   imagemagick-native: 556.9ms per iteration
   Winner: **imagemagick** is _224%_ faster
4. Above wallpaper, HD,153.9 kB, 960x540
   imagemagick:       37.4ms per iteration
   imagemagick-native: 48.59ms per iteration
   Winner: **imagemagick** is _129%_ faster
5. Above wallpaper, HD, 965.4 kB, 2880x1620
   imagemagick:       178.96ms per iteration
   imagemagick-native: 440.14ms per iteration
   Winner: **imagemagick** is _254%_ faster

As far as I can tell, using imagmagick-native makes sense, only with small files.
What is your input on this?

With thanks,
Laszlo

**Comment by hbakhtiyor** [comment]
from [this performance test](http://sharp.dimens.io/en/stable/performance/) imagemagick is a bit fast than imagemagick-native

what do you think?
