### ISSUE TITLE
background none in svg2png covert

### ISSUE THREAD

**Issue by vadimgoncharov** [elad/node-imagemagick-native#63]
When I converting svg with transparent background to png, I get png with white background color instead of transparent.

If I run "convert -background none file.svg file.png" from command line then everything works fine.
 
How can I add "-background none" parameter in convert API?

**Comment by enagorny** [comment]
@vadimgoncharov Did you find any workaround or fix for this?

**Comment by romuloctba** [comment]
+1
Oh I need it too

**Comment by deepakvenkat** [comment]
Is this going to be merged?

**Comment by facilitateur** [comment]
Hi, if you use svg2png API with npm, you can update "converter.js" file on lib directory

line 8 : add backgroud-color: white;
```
var HTML_PREFIX = "<!DOCTYPE html><style>html, body { margin: 0; padding: 0; } " +
                  "svg { position: absolute; top: 0; left: 0; background-color:white; }</style>";
```
