### ISSUE TITLE
load base64 string as SrcData

### ISSUE THREAD

**Issue by kadosh1000** [elad/node-imagemagick-native#94]
is there any way to load a base64 string as my data source? also tried to send it as a buffer using 

new Buffer(base64String, 'base64')

**Comment by elad** [comment]
Pull requests welcome. :)

**Comment by fabien-h** [comment]
I'm exactly on the same issue :)

If a binary is needed, how do I convert my base64 to a binary buffer ? (this question may seems stupid)

**Comment by elad** [comment]
http://stackoverflow.com/a/14573049

**Comment by fabien-h** [comment]
Thank you. I did that, but apparently, the problem is elsewhere. I quit bothering you here.
