### ISSUE TITLE
Magick++-config is depreciated

### ISSUE THREAD

**Issue by steelbrain** [elad/node-imagemagick-native#95]
https://bugs.launchpad.net/ubuntu/+source/imagemagick/+bug/1449697/comments/1
^ it's not available in `/usr/bin/` in the binary packages for Ubuntu 15.04

**Comment by lovell** [comment]
Assuming a 64-bit system, the following command will create a symlink for a temporary workaround:
```sh
sudo ln -s /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/bin-Q16/Magick++-config /usr/bin/Magick++-config
```
The proper fix is for the `binding.gyp` file in this module to first try `pkg-config` to locate Imagemagick's header files, then fall back to `Magick++-config` for older versions.

**Comment by steelbrain** [comment]
I did that symlink but it didn't work for me :(
I can't post the error message now but I if you need it just let me now

**Comment by Alan01252** [comment]
This worked for me on Ubuntu

sudo apt-get install libmagick++-dev

**Comment by steelbrain** [comment]
@Alan01252 It might work on `12.04`, but it doesn't work on `14.04`

**Comment by Alan01252** [comment]
:( it did for me!

Cdeploy@engine:/srv/opt/agricameraifu/lib$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

**Comment by steelbrain** [comment]
Sorry by `14.04` I meant `15.04`
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.04
Release:	15.04
Codename:	vivid
```

**Comment by Alan01252** [comment]
Ahh sorry @steelbrain I should have put version in first post :( GL with 15.04 sorry I can't help more.

**Comment by simonh1000** [comment]
Any fix yet for the 15.x?

**Comment by cartuchogl** [comment]
#164 close this
